### ISSUE TITLE
Dealing with master track for knobs and banks

### ISSUE THREAD

**Issue by leonardder** [jcsteh/reaKontrol#2]
I just realised that I introduced some inconsistency in #1 with regard to how the knobs change track parameters.

1. CSurf_TrackToID creates a 0 based ID, where 0 stands for the master track
2. Banks are 0 based as well. `int numInBank = id % BANK_NUM_TRACKS;`
3. Thus, the first bank starts with master and ends with 7, the second bank starts with 8 and ends with 15, etc.
4. However, in #1, the first knob maps to track 1, not to the master track. This is because I somehow forgot about the master track when writing this. This means that knob 8 changes track 8, which is in the next bank.

I'm not sure whether I'd like changing this. Having knob one for the master track seems to be a bit confusing, especially when the master track is hidden. On the other hand, I'd like things to be consistent. So either I'd vote for ignoring the master track altogether, or map knob 1 to master, knob 2 to track 1, etc.

**Comment by jcsteh** [comment]
For now at least, I think we should allow the master track:

1. It's hidden, but it doesn't have to be; you can make it visible.
2. The Komplete Kontrol manual does suggest that the master track can be selected for at least some DAWs, so we're not doing something totally unique here.
3. From what I can see from the surface code (and I believe I've also heard REAPER users mention this), the master track can be manipulated on other surfaces.

**Comment by brummbrum** [comment]
Hi guys, I merged Leonard's recent changes incl the track / knob numbering update into my forked master. All changes work fine, could not find any issues. I added simple track navigation in mixer view via the top row buttons. Currently limited to 99 tracks (see comments). Do you know of an API call that could be used instead of the action to support unlimited number of tracks?

**Comment by brummbrum** [comment]
Problem solved. In my latest branch https://github.com/brummbrum/reaKontrol/tree/BankSelection I now implemented track navigation via the top row buttons in mixer view using direct API calls instead of calling actions. Thus the limitation is gone. Also updated a few other things related to the mixer view like refreshing the screens and removing tracks from being listed in the last bank which are actually left overs from the previous bank. Will add bank selection as soon as I find the time and then merge into my master. That could be a good be a good point in time to merge into your master, James?
