### ISSUE TITLE
Publish to ReaPack

### ISSUE THREAD

**Issue by leonardder** [jcsteh/reaKontrol#35]
We had a similar issue for Osara, but in the case of ReaKontrol, there is currently no installer. It might be beneficial to publish ReaKontrol on ReaPack for it to be found more easily.

**Comment by jcsteh** [comment]
I've abandoned my version of this in favour of @brummbrum's fork, since I don't have time to work on this and the fork is much further ahead. I considered deleting my repository and having it redirect to @brummbrum's, but the problem is that this would prevent me from contributing any changes, since I wouldn't be able to create pull requests without a repository.
